---
- set_fact: golang_version=1.5.1
- name: Install base packages
  action: apt name={{ item }} state=latest
  with_items:
    - tree
    - watch
    - htop
    - git
- include: docker.yml
- include: git.yml
- include: go.yml